package gamesdb

// Code generated from the genre dictionary built against a real collection;
// edit by hand or regenerate. Keys are "Genre" or "Genre/Sub-genre"; the
// values are the folder names (as normaliseGenreFolder leaves them) that
// mean that genre.

var genreFolders = map[string][]string{
	"Action":                       {"action", "action (general)", "action general", "general action", "action - general", "arcade style action"},
	"Action Adventure":             {"action adventure", "action-adventure", "action - adventure", "general action adventure", "action adventure - general", "open world action adventure", "linear action adventure", "action adventure - linear", "action adventure - open world"},
	"Adventure":                    {"adventure", "general adventure", "adventure - general", "adventures"},
	"Adventure/Text Adventure":     {"text adventure", "interactive fiction", "text adventures"},
	"Adventure/Point & Click":      {"point & click", "point and click", "point & click adventure"},
	"Adventure/Visual Novel":       {"visual novel", "visual novels"},
	"Beat 'em Up":                  {"beat 'em up", "beat em up", "beat'em up", "beat 'em ups", "beat em ups", "beat'em ups", "brawler", "brawlers"},
	"Board & Card":                 {"board & card games", "board & card", "board and card games", "board games", "boardgames", "board game", "cards boardgames", "cards", "card games", "card game", "chess", "mahjong"},
	"Casino":                       {"gambling", "casino", "pachinko", "slots", "casino & gambling", "gambling & casino"},
	"Educational":                  {"edutainment", "kids edutainment", "educational", "educatif", "compilations - educational", "fun + learning"},
	"Fighting":                     {"fighting", "fighters", "fighter", "fighters (1v1)", "fighting games", "vs fighting", "versus fighting"},
	"Fighting/2D Fighting":         {"fighters 2d", "2d fighters", "fighting - 2d", "2d fighting"},
	"Fighting/3D Fighting":         {"fighters 3d", "3d fighters", "fighting - 3d", "3d fighting"},
	"Maze":                         {"maze", "mazes", "maze games"},
	"Music & Rhythm":               {"music n rythm", "music n rhythm", "music & rhythm", "music rhythm", "rhythm", "rhythm games", "dance"},
	"Party":                        {"party & minigame", "party & minigames", "minigames", "party"},
	"Pinball":                      {"pinball", "video pinball"},
	"Platform":                     {"platformers", "platformer", "platform", "platform games", "all platformers", "platformer - 2d", "2d platformers", "3d platformers", "action & platforming", "action platformer", "action platformers", "d platformers"},
	"Puzzle":                       {"puzzle", "puzzles", "general puzzle", "puzzle - general", "all puzzle games", "puzzle games"},
	"Puzzle/Action Puzzle":         {"action puzzle", "puzzle - action"},
	"Puzzle/Matching Puzzle":       {"matching puzzle", "puzzle - matching", "matching"},
	"Puzzle/Stacking Puzzle":       {"stacking puzzle", "puzzle - stacking", "stacking"},
	"Puzzle/Logic Puzzle":          {"logic puzzle", "puzzle - logic"},
	"Puzzle/Versus Puzzle":         {"puzzle - 2-player vs", "2 player puzzle (vs.)", "player puzzle (vs.)"},
	"Racing":                       {"racing", "racing games", "racing action", "racing - multiplayer", "racing - 2 player", "racing - 3-4 players (multitap)"},
	"Racing/Arcade Racing":         {"arcade racing", "racing - arcade style", "arcade racing - automobile", "arcade racing - other", "arcade racing - futuristic", "futuristic racing", "combat racing"},
	"Racing/Simulation Racing":     {"simulation racing", "racing sim", "racing - simulation style", "racing simulation"},
	"Racing/Vehicular Combat":      {"vehicular combat", "car combat"},
	"RPG":                          {"role playing games", "role playing game", "rpgs", "rpg", "general rpg", "rpg - general", "all role playing games", "role-playing", "roleplaying"},
	"RPG/Action RPG":               {"action rpg", "rpg - action", "action rpgs"},
	"RPG/Japanese RPG":             {"japanese style rpg", "rpg - japanese style", "classic jrpg", "jrpg", "jrpgs", "trainer rpg"},
	"RPG/Western RPG":              {"western style rpg", "rpg - western style", "western rpg", "dungeon crawler", "dungeon crawlers"},
	"RPG/Roguelike":                {"roguelike rpg", "roguelike", "roguelikes"},
	"Shooter":                      {"shooters", "shooter", "all shoot 'em ups"},
	"Shooter/Shoot 'em Up":         {"shoot 'em up", "shoot 'em ups", "shoot em up", "shoot em ups", "shoot'em up", "shmups", "shmup", "shooter - vertical", "shooter - horizontal", "vertical shooter", "horizontal shooter"},
	"Shooter/Run 'n' Gun":          {"run 'n' gun", "run 'n' guns", "run n gun", "run 'n gun", "run 'n' gun - platformer style"},
	"Shooter/First Person Shooter": {"fps", "first person shooters", "first person shooter"},
	"Shooter/Light Gun":            {"lightgun", "light gun", "light gun zapper", "light gun games"},
	"Shooter/Rail Shooter":         {"rail shooters", "rail shooter"},
	"Shooter/Third Person Shooter": {"third person shooters", "third person shooter"},
	"Simulation":                   {"simulation", "simulations", "all simulation", "simulation style", "virtual simulation", "simulation - general", "simulator"},
	"Simulation/Flight":            {"flight", "flight simulation", "simulation - flight", "flight combat", "flight sim"},
	"Simulation/Vehicle":           {"vehicle simulation", "vehicle simulator"},
	"Simulation/Management":        {"management", "management sim", "business simulation"},
	"Sports":                       {"sports", "sport", "sports sim", "other sports", "sports - other", "sports games", "all sports"},
	"Sports/Soccer":                {"soccer", "sports - soccer", "football (soccer)"},
	"Sports/American Football":     {"football (american)", "sports - football (american)", "american football"},
	"Sports/Football":              {"football"},
	"Sports/Baseball":              {"baseball", "sports - baseball"},
	"Sports/Basketball":            {"basketball", "sports - basketball"},
	"Sports/Golf":                  {"golf", "sports - golf"},
	"Sports/Tennis":                {"tennis", "sports - tennis"},
	"Sports/Hockey":                {"hockey", "ice hockey", "sports - hockey"},
	"Sports/Boxing":                {"boxing", "sports - boxing"},
	"Sports/Wrestling":             {"wrestling", "sports - wrestling"},
	"Sports/Bowling":               {"bowling"},
	"Sports/Fishing":               {"fishing", "sports - fishing"},
	"Sports/Athletics":             {"athletics", "olympics", "track & field"},
	"Sports/Volleyball":            {"volleyball"},
	"Sports/Billiards":             {"billiards", "pool", "snooker"},
	"Sports/Skateboarding":         {"skateboarding", "skate skateboard", "skate"},
	"Sports/Winter Sports":         {"ski & snowboarding", "ski snowboard", "snowboarding", "skiing", "winter sports"},
	"Strategy":                     {"strategy", "strategy - general", "general strategy", "strategy games", "tactical", "traditional war", "war", "wargames"},
	"Strategy/Turn Based Strategy": {"turn based", "turn based strategy", "strategy - turn-based", "turn-based strategy"},
	"Strategy/Real Time Strategy":  {"real time", "real time strategy", "strategy - real-time", "rts"},
	"Survival Horror":              {"survival horror", "survival", "horror"},
	"Trivia & Quiz":                {"trivia & game show", "game show & trivia", "quiz", "trivia", "quiz games"},
}
