package virtualinput

import "strings"

// KeyboardMap names the virtual keyboard's keys (uinput key codes), for
// BIOS skip sequences ("key:enter") and SAMenu's own presses (F9 to show
// the console). The names are the ones the keyboard detector reports for
// a key (see keyboardscancodes.txt), so a key pressed in the BIOS skip
// editor can always be pressed again. A few extra spellings are accepted
// too ("escape", "return", "pgup"...).
var KeyboardMap = map[string]int{
	"esc":        1,
	"escape":     1,
	"1":          2,
	"2":          3,
	"3":          4,
	"4":          5,
	"5":          6,
	"6":          7,
	"7":          8,
	"8":          9,
	"9":          10,
	"0":          11,
	"-":          12,
	"=":          13,
	"backspace":  14,
	"tab":        15,
	"q":          16,
	"w":          17,
	"e":          18,
	"r":          19,
	"t":          20,
	"y":          21,
	"u":          22,
	"i":          23,
	"o":          24,
	"p":          25,
	"[":          26,
	"]":          27,
	"enter":      28,
	"return":     28,
	"ctrl":       29,
	"lctrl":      29,
	"leftctrl":   29,
	"a":          30,
	"s":          31,
	"d":          32,
	"f":          33,
	"g":          34,
	"h":          35,
	"j":          36,
	"k":          37,
	"l":          38,
	";":          39,
	"'":          40,
	"`":          41,
	"shift":      42,
	"lshift":     42,
	"leftshift":  42,
	"\\":         43,
	"backslash":  43,
	"z":          44,
	"x":          45,
	"c":          46,
	"v":          47,
	"b":          48,
	"n":          49,
	"m":          50,
	",":          51,
	".":          52,
	"/":          53,
	"rshift":     54,
	"rightshift": 54,
	"alt":        56,
	"lalt":       56,
	"leftalt":    56,
	" ":          57,
	"space":      57,
	"caps":       58,
	"capslock":   58,
	"f1":         59,
	"f2":         60,
	"f3":         61,
	"f4":         62,
	"f5":         63,
	"f6":         64,
	"f7":         65,
	"f8":         66,
	"f9":         67,
	"f10":        68,
	"num":        69,
	"numlock":    69,
	"scroll":     70,
	"scrolllock": 70,
	"f11":        87,
	"f12":        88,
	"home":       102,
	"up":         103,
	"pgup":       104,
	"pageup":     104,
	"left":       105,
	"right":      106,
	"end":        107,
	"down":       108,
	"pgdn":       109,
	"pagedown":   109,
	"ins":        110,
	"insert":     110,
	"del":        111,
	"delete":     111,
	"voldn":      114,
	"volumedown": 114,
	"volup":      115,
	"volumeup":   115,
	// shift
	"~":    -41,
	"!":    -2,
	"@":    -3,
	"#":    -4,
	"$":    -5,
	"%":    -6,
	"^":    -7,
	"&":    -8,
	"*":    -9,
	"(":    -10,
	")":    -11,
	"_":    -12,
	"+":    -13,
	"plus": -13,
	"{":    -26,
	"}":    -27,
	"|":    -43,
	":":    -39,
	"\"":   -40,
	"<":    -51,
	">":    -52,
	"?":    -53,
	// The numeric keypad, and a few more the detector can report.
	"numpad0":     82,
	"numpad1":     79,
	"numpad2":     80,
	"numpad3":     81,
	"numpad4":     75,
	"numpad5":     76,
	"numpad6":     77,
	"numpad7":     71,
	"numpad8":     72,
	"numpad9":     73,
	"numpad.":     83,
	"numpad/":     98,
	"numpad*":     55,
	"numpad-":     74,
	"numpad+":     78,
	"numpadenter": 96,
	"printscreen": 99,
	"pause":       119,
	"rightctrl":   97,
	"rightalt":    100,
	"leftgui":     125, // the Windows / Command keys
	"rightgui":    126,
}

// ToKeyboardCode looks up a key by name ("a", "enter", "f9"), ignoring
// case.
func ToKeyboardCode(name string) (int, bool) {
	v, ok := KeyboardMap[strings.ToLower(strings.TrimSpace(name))]
	return v, ok
}
